### ISSUE TITLE
Allow removing view cursor to "un-highlight" all lines

### ISSUE THREAD

**Issue by coloursofnoise** [awesome-gocui/gocui#108]
Demonstrated using `_examples/mouse.go`
- Current behaviour:
![gocui_mouse_bug](https://user-images.githubusercontent.com/53288101/143140270-003aa63a-54f0-4dff-ab91-74941c5f6291.gif)
- Desired behaviour:
![gocui_mouse_fixed](https://user-images.githubusercontent.com/53288101/143140437-742ceb33-0717-4a54-974e-b41f00b9bfcc.gif)

The fix displayed above was done by adding a `View.RemoveCursor` method to set the cursor position to `(-1, -1)`, which was called during `Gui.onKey` on the last view selected by the mouse.
[Patch File](https://github.com/awesome-gocui/gocui/files/7591462/demo.txt) (as `.txt` due to GitHub restrictions)

This implementation is presumeably a bad idea due to setting the cursor position to an invalid point, so other ideas would be appreciated.

**Comment by dankox** [comment]
This is quite a specific solution to specific problem. There is no restore cursor position after it's removed (when the view is activated thru other means than mouse) and it also doesn't work when user wants to keep the line highlighted for some reason. Although I'm not sure if the keep-highlighted actually works even now :)

I think the correct solution would be to implement something like `gocui.MousePosition()` function, which can return mouse position on the screen which can be then used to check what View is underneath. This way, user can turn `v.Highlighted` on and off as needed.

**Comment by coloursofnoise** [comment]
That sounds much more reasonable.
I probably won't try to implement it until I'm a bit more familiar with the library so it's free for anyone else to do if they wish.
