### ISSUE TITLE
Help with selected row highlight

### ISSUE THREAD

**Issue by sangdth** [awesome-gocui/gocui#129]
Hi, first thanks for efforts to keep the gocui alive :D 

I don't see the Discussion feature, so please forgive me to use issue to ask.

So far I can make some simple views, and the selected row works well. But it only show the background of text only, not full row. I attach the screenshots:

Current situation:
![Screenshot 2023-05-17 at 8 57 34](https://github.com/awesome-gocui/gocui/assets/1083478/b7605fa6-8b9b-4d09-8e74-b50e3effdebc)

Expected:
![Screenshot 2023-05-17 at 8 58 05](https://github.com/awesome-gocui/gocui/assets/1083478/7be29962-16a1-4b4d-96f7-21ac7b59525f)
(I took from lazygit, also created with gocui)

The code:

```
if v, err := g.SetView(issuesView, 0, projectViewHeight+1, sideBarWidth, maxY-1); err != nil {
	if err != gocui.ErrUnknownView {
		return err
	}
	v.Title = " Issues "
	v.Highlight = true
	v.SelBgColor = gocui.ColorGreen
	v.SelFgColor = gocui.ColorBlack
}

```

I tried to search inside the lazygit repo, try to learn from them but my limited knowledge can't do much.

Could someone give a hint, really appreciate it <3

**Comment by zocker-160** [comment]
you probably forgot about this issue, but you have to simply fill the entire line with the space rune, then it will highlight the way you expect.

**Comment by sangdth** [comment]
Thanks @zocker-160 , I do not forget, I just changed company and don't use this app any more so I do not develop it further.
