### ISSUE TITLE
Improve get terminal window size in the docker container

### ISSUE THREAD

**Issue by skanehira** [awesome-gocui/gocui#15]
**Describe the feature you'd like**
The current gocui dosn't work in the docker container's endpoint because the termbox cannot get terminal window size when run the container.

**Describe alternatives you've considered**
Improve get terminal window size like as follows.
When we use the container must to be wait SIGWINCH.

https://github.com/skanehira/docui/commit/aa1739a8f9a1d5284239021691631fca0b96d019

**Additional context**
We have to improve the termbox?
Or gocui?
I want to discussion.

**Comment by mjarkk** [comment]
I think this library should work everywhere where it can so also in a docker container's endpoint.  
This is probably better to change in GoCui because Termbox seems to me like a bear bones library just to get some UI in the terminal.

**Comment by glvr182** [comment]
I back this feature. I think it would be best to do this in gocui since.

**Comment by skanehira** [comment]
Merged  #18
