### ISSUE TITLE
information about this fork

### ISSUE THREAD

**Issue by mjarkk** [awesome-gocui/gocui#17]
**Describe the feature you'd like**
In the readme or in docs add a section about this fork with information about why we forked it and a number of important changes this fork has compared to jromartin's

**Describe alternatives you've considered**  
/

**Additional context**
In general it would be nice to have better documentation, related to (#12).

**Comment by glvr182** [comment]
Agreed, this can also be linked to more examples and maybe more features #16

**Comment by mjarkk** [comment]
This issue can be closed when #26 is merged in

**Comment by mjarkk** [comment]
#26 is now merged in closing this issue
