### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by glvr182** [awesome-gocui/gocui#20]
**Describe the feature you'd like**
To make Gocui a truly amazing project, we need an icon. If anyone knows a graphics designer who would do this for an opensource project (to have another piece of art added to their portfolio), please do let us know. 

**Describe alternatives you've considered**
Making it myself but I am absolutely terrible with graphics.

**Additional context**
/

**Comment by mjarkk** [comment]
This is also already noted in the about repo,  
I’m not a active illustrator/photoshop user but I do know how to make a decent logo. I can give it a try and see how far I come

**Comment by mjarkk** [comment]
I've created this logo, ([@awesome-gocui/about/logo](https://github.com/awesome-gocui/about/blob/master/logo/logo.png))  
![logo](https://github.com/awesome-gocui/about/blob/master/logo/logo.png?raw=true "logo")

**Comment by glvr182** [comment]
Looks awesome! I say we put this one in @awesome-gocui/about

**Comment by mjarkk** [comment]
Dune, it's now in the about readme

**Comment by glvr182** [comment]
Closing this since it has been implemented
