### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by josharian** [awesome-gocui/gocui#37]
Thanks for the speedy review of #36 (for #33)! May I request that you add a new tag/released version so that folks like me using 1.13 can pick up the bug fix without a replace directive in our go.mod? Thanks!

**Comment by glvr182** [comment]
@josharian You're right, it is time for a new release. I shall however release v0.6.0 since there are lots of other improvements aside from this fix.

**Comment by glvr182** [comment]
You can checkout version v0.6.0 now! Let me know how it goes!

**Comment by josharian** [comment]
Thanks!
