### ISSUE TITLE
[BUG] Exits on Open

### ISSUE THREAD

**Issue by Rudi9719** [awesome-gocui/gocui#44]
**Describe the bug**
After converting from jroimartin/gocui to awesome-gocui (adding params to g.NewGui(), and g.SetView()) my projectnow exits cleanly upon opening rather than starting the main loop.

**To Reproduce**
1. Compile project
2. Start Project

**Expected behavior**
TUI with 4 views should appear, and populate with text as they did with jroimartin/gocui

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version go1.13.1 linux/amd64

**Additional context**
https://github.com/Rudi9719/kbtui/tree/awesome-gocui

I began migrating to this (maintained) fork of gocui to implement features that were missing from the original, however it looks like it just closes after `gocui.NewGui()` it doesn't return the normal tuple, and just exits.

**Comment by mjarkk** [comment]
Thanks for creating the issue,  
i'll look into your project later today and see if we can fix your issue.

**Comment by mjarkk** [comment]
I've looked into your code and found the problem.  
We do the unknown view check a bit different than the original repo, in your layout function change these checks:
```go
// from this:
if err != gocui.ErrUnknownView {
  return err
}

// to this:
if !gocui.IsUnknownView(err) {
  return err
}
```
This this behavior can also be found in the example projects: [_examples/layout.go#L15](https://github.com/awesome-gocui/gocui/blob/master/_examples/layout.go#L15)

**Comment by mjarkk** [comment]
I've created a pr in your repo to fix the problem: https://github.com/Rudi9719/kbtui/pull/1

**Comment by Rudi9719** [comment]
Thanks! Merged in
