### ISSUE TITLE
version of go-runewidth

### ISSUE THREAD

**Issue by MichaelMure** [awesome-gocui/gocui#52]
Just a FYI, you might want to update the go-runewidth version to the latest as it at least fix the width of a bunch a characters. Those bugs tends to be quite annoying to track down.

**Comment by mjarkk** [comment]
Thanks for notifying I've put up a pr to fix it #53

**Comment by MichaelMure** [comment]
You might want to enable dependabot to get notified when a dep has a new version and have a PR ready automatically. I'm using it for my projects, it's great.
