### ISSUE TITLE
Add ability to change view visibility

### ISSUE THREAD

**Issue by strang1ato** [awesome-gocui/gocui#55]
It would be nice if there was Hide, Unhide view methods like in that unmaintained repo in this commit: https://github.com/grafov/gocui/commit/dfc721a26b344a30646e3e236544bcf82f9c0c2c

**Comment by strang1ato** [comment]
Or by using capital `Visible` instead of `visible` to omit unneed functions, like I did it on my fork https://github.com/oltarzewskik/gocui/commit/b31b18ed36829af77d4e5508ae7d4bcc55cf2919

**Comment by mjarkk** [comment]
I think we already have that :)  
https://github.com/awesome-gocui/gocui/blob/55e71cf05a1839a750044dd2198fe7a5cca81fa3/view.go#L61

**Comment by strang1ato** [comment]
Oh, sorry for that. Thanks :smile:
