### ISSUE TITLE
[BUG] Rune-based keybindings do not work without a current view

### ISSUE THREAD

**Issue by fawick** [awesome-gocui/gocui#56]
**Describe the bug**
I have a Gui without a currentView and only with global keybindings. I ran into the problem that keybindings based on `rune` would not work for me while keybindings based on `gocui.Key` were still working. I traced the issue a bit and found that the reason seems to be that no current view is set. I describe this under "Additional Context" below. The minimum viable reproduction is based upon one of the files in `_example/`.

**To Reproduce**
1. Edit `_examples/table.go`
2. Add a second keybinding below the Ctrl-C like this:
```go
if err := g.SetKeybinding("", 'q', gocui.ModNone, quit); err != nil {
    log.Panicln(err)
}
```
3. Run with `go run table.go`
4. Press the `q` key

**Expected behavior**
With `q` pressed, the application should quit.

**Environment (please complete the following information):**
 - OS: Tested on Linux, Windows 7, Windows 10
 - Version: gocui v0.6.0

**Additional context**
I chose `table.go` as it is the only example without a call to `func (g *Gui) SetCurrentView(name string)```. If you amend the method `func (t *Table) Layout(g *gocui.Gui) error` function in `table.go` with a call to `SetCurrentView` right before the return at the end like in the following code snippet, then the  keypress will work.

```go
g.SetCurrentView(t.name)
```

My layman's guess would be that the culprit is in https://github.com/awesome-gocui/gocui/blob/master/gui.go#L790:
- `v` is `nil` in the call to `execKeybindings`, because `g.currentView` is `nil` in the call to `onKey` in https://github.com/awesome-gocui/gocui/blob/master/gui.go#L745
- `kb.ch` is not 0, but is set to a rune.
- Hence, the if-condition never resolves to true, `globalKb` is never assigned a non-nil value, and `execKeybinding` is never called for the global keybinding.

**Comment by glvr182** [comment]
Confirmed that it stil exists in master, gonna have a look at it now

**Comment by glvr182** [comment]
PR is up, you can test it if you want

**Comment by fawick** [comment]
I applied the patch from #57 against my local copy of 0.6.0 and can confirm that the patch fixes the issue.

**Comment by fawick** [comment]
Thanks for addressing and fixing this swiftly!

**Comment by glvr182** [comment]
No problem, hopefully we'll create a new release soon. But for now you can just use the master branch
