### ISSUE TITLE
[BUG] SelFgColor and SelBgColor are not used for Highlight anymore

### ISSUE THREAD

**Issue by kanbara** [awesome-gocui/gocui#59]
**Describe the bug**
Apparently, SelFgColor and SelBgColor are not used anymore in highlighted frames. The original SetRune implementation checked the highlight state, and the current SetRune only bolds the fgColor, as seen in this commit https://github.com/awesome-gocui/gocui/commit/d9a7952a95539a75d4f64ccdfe30bd09b549e2a9

**To Reproduce**
```
v.Highlight = true
v.SelFgColor = gocui.ColorYellow
```

Observe the highlighted color is only bolded.

**Expected behavior**
I expected to be able to use SelFgColor and SelBgColor to set the color. I'm under the impression that using SetHiglight and manually tracking the highlight state is what you expect users to do, then? Otherwise, I would like to bolden the text, but also check if the SelFgColor and SelBgColor are not ColorDefault, and if so, use them too.

What do you think?

Additionally, the documentation is then out of date. I understand this project was taken over to resurrect it (I switched today from jroimartin/gocui to this one) and I don't get why the documentation-- even on the main page lacking the overlap flag-- has not been updated.

**Comment by glvr182** [comment]
You're right we have to update a lot of documetation. We haven't been active a lot since starting this project. I'll try to fix this and add documentation ASAP.

**Comment by glvr182** [comment]
should be fixed in #61

**Comment by kanbara** [comment]
awesome, that commit looks good. thanks!

**Comment by glvr182** [comment]
Sorry for taking so long to reply, should really stick more time in this. After all we forked because the original author abandoned it... Now we are doing the same thing
