### ISSUE TITLE
Frame color for Views

### ISSUE THREAD

**Issue by dankox** [awesome-gocui/gocui#71]
Hi,
I wanted to ask, if I could create a PR for adding frame color for seperate views. Basically it would add new color attribute to view for frame and title color.

I had created a fork with that change which I'm using in my project. But I was hoping something like that could be added to this repo too.

Here is my commit in the forked repo: https://github.com/dankox/gocui/commit/a7e8d20a79e69a488327eaaeeeb8ce0c62d67e3c

**Comment by mjarkk** [comment]
Seems like an oke change to me.  
Feel free to create a PR for this!

**Comment by glvr182** [comment]
sounds good! go for it!

**Comment by dankox** [comment]
Cool. I created a PR, but I added there a bit more. It's still related to the frames, so I hope you won't mind. 
If you feel like the added customization is not ok, I can revert it to color customization only.
