### ISSUE TITLE
Release v1.0.0?

### ISSUE THREAD

**Issue by mjarkk** [awesome-gocui/gocui#79]
As it has now been 2 months since the creation of the v1.0.0 pre-release versions and there has only been 1 issue should we release v1.0.0?  
@dankox What are your thoughts?

**Comment by dankox** [comment]
Sorry for delay, had a vacation :)

Yeah, that makes sense. However, I wanted to create PR with some updates to the documentation, so maybe this could be done before. I was writing some migration "tips" when I was moving to the beta release (like how to easily change the error handling across the project and the `MoveCursor` function change).    
I would be able to do this PR in few days (have to catch up with my real work first :). So it's up to you, if you think it might be worth the wait or you want to push it out sooner?

**Comment by mjarkk** [comment]
Ah great!, i'll wait for your PR and after that we can create v1
