### ISSUE TITLE
Add ability to use tcell simulated screen for testing gocui

### ISSUE THREAD

**Issue by lawrencegripper** [awesome-gocui/gocui#86]
**Describe the feature you'd like** (Happy to PR this feature)
tcell supports a simulated screen, this allows you to write unit tests which provide input and then assert about the content drawn on the screen.

https://github.com/gdamore/tcell/blob/master/sim_test.go

Adding in this feature by either exposing the tcell simulated screen or a wrapper to abstract it but allow input of keys and validation of the resulting content drawn would help building testable UI apps.

**Describe alternatives you've considered**
Currently I do some [horrible things in our CI pipeline to create a "real" screen on the CI box](https://github.com/lawrencegripper/azbrowse/blob/cd81075c8702b3d6f0b318f4eb90f58ca540a690/scripts/ci_release.sh#L76) then spin up a xterm instance and pipe the results back.

**Additional context**
Here is an example of another tcell based project using the simulated screen to write some nice tests. https://github.com/zyedidia/micro/blob/c0907bb58e35ee05202a78226a2f53909af228ca/cmd/micro/micro_test.go#L183

**Comment by mjarkk** [comment]
That would be very handy and i could imagine make testing for a lot of programs a lot more accessible so yea i'm open for this feature!  
feel free to create a PR for this!

**Comment by lawrencegripper** [comment]
Cool, going to take a run at this now and see how far I get. 

Given the rest of `gocui` abstracts the underlying `tcell` lib I'm going to wrap the features so in theory future work could change the underlying `tcell` driver and reimplement the funcs using another lib without users needing to make changes.

**Comment by mjarkk** [comment]
Can we now close this issue?

**Comment by lawrencegripper** [comment]
Yup 🥳
